spring.application.name=backend

#Conexión con base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/ventas
spring.datasource.username=postgres
spring.datasource.password=1115120175

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=mVDa5C/ydsJY0SUliP+AwFwK7ZOmlDZfAEyGc3I3HdKmc9c4ivoOv4CrHqSQi6WuI4FZW1mjJxTmsxJPjuPXeQ==
app.jwt.expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000

# CORS
app.cors.allowed-origins=http://localhost:5173

logging.level.org.springframework.security=TRACE
